from glbdata import *
from eval_kdj import eval_kdj
from eval_macd import eval_macd
from eval_rsi import eval_rsi
from plot_candle import plot_candle
from mod_trading import mod_trading
from mod_update_pos import mod_update_pos
from eval_strategy1 import eval_strategy1
from mod_run_strategy import mod_run_strategy
from mod_run_strategy import mod_run_strategy_process
from mod_schedule import mod_schedule
from mod_pickup_pos import mod_pickup_pos
from rpt_total_capital import rpt_total_capital
from get_stock_data import get_stock_data
from get_stock_data import get_stock_data_process